### ISSUE TITLE
various cmake versions

### ISSUE THREAD

**Issue by kkretsch** [r4yan2/peaks#1]
I tried an install using a current debian 9. This has "only" cmake 3.7.2 as default version.
As the subfolders refer to different higher versions I wonder if this is intended or if we could rewrite thos cmake files to use version 3.7.2 instead.

**Comment by r4yan2** [comment]
Acknowledge.
Honestly the codebase is somewhat "messy" here and there (you found one example), because multiple people where involved in the project at different times and there was no agreement or convention on which tools/version would be used.
I'm just finishing another module (the database dump/backup), and I'll be back on this in some minute. Thank you for the feedback
