### ISSUE TITLE
running peaks 

### ISSUE THREAD

**Issue by skasks** [r4yan2/peaks#9]
Running:

bin$ ./peaks 
Caught exceptionThrow location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::bad_any_cast>
std::exception::what: boost::bad_any_cast: failed conversion using boost::any_cast

(took me some time to notice, that the error is thrown if started without any arguments only)

If one uses other import options than --fastimport:
bin$ ./peaks import --path ~/1/
searching config file peaks_config
config file found!
08/13/19 11:23:37:      Starting unpacker
Threads: 2
Searching for certificates in: "/home/ubuntu/1/"
Found 1 keys to import
Key per Thread: 1
08/13/19 11:23:37:      Starting dump read
Segmentation fault (core dumped)

The documented commands:

./peaks import -p path-to-keydump --fastimport
./peaks build

run without errors, filling to tables:
MariaDB [(none)]> SELECT TABLE_ROWS, TABLE_NAME     FROM INFORMATION_SCHEMA.TABLES       WHERE TABLE_SCHEMA = 'gpg_keyserver';
+------------+-------------------------+
| TABLE_ROWS | TABLE_NAME              |
+------------+-------------------------+
|          0 | selfSignaturesMetadata  |
|       1870 | gpg_keyserver           |
|          0 | KeyStatus               |
|         85 | ptree                   |
|          0 | removed_hash            |
|          0 | broken_keys             |
|          0 | UserID                  |
|          0 | Pubkey                  |
|          0 | Signatures              |
|       NULL | Signature_no_issuing_fp |
|          0 | Unpacker_errors         |
|          0 | revocationSignatures    |
|          0 | SignatureStatus         |
|          0 | UserAttribute           |
|       NULL | key_primary_userID      |
+------------+-------------------------+

Another ./peaks unpack says:
/bin$ ./peaks unpack
searching config file peaks_config
config file found!
limiting analysis at 10000 keys
key per thread: 1117
limiting analysis at 10000 keys
No data to process, exiting

but has filled other tables as well:

MariaDB [(none)]> SELECT TABLE_ROWS, TABLE_NAME     FROM INFORMATION_SCHEMA.TABLES       WHERE TABLE_SCHEMA = 'gpg_keyserver';
+------------+-------------------------+
| TABLE_ROWS | TABLE_NAME              |
+------------+-------------------------+
|       3365 | selfSignaturesMetadata  |
|       1870 | gpg_keyserver           |
|          0 | KeyStatus               |
|         85 | ptree                   |
|          0 | removed_hash            |
|          0 | broken_keys             |
|       3174 | UserID                  |
|       5082 | Pubkey                  |
|       7862 | Signatures              |
|       NULL | Signature_no_issuing_fp |
|         48 | Unpacker_errors         |
|        157 | revocationSignatures    |
|          0 | SignatureStatus         |
|         24 | UserAttribute           |
|       NULL | key_primary_userID      |
+------------+-------------------------+

**Comment by r4yan2** [comment]
> bin$ ./peaks
> Caught exceptionThrow location unknown (consider using BOOST_THROW_EXCEPTION)
> Dynamic exception type: boost::wrapexceptboost::bad_any_cast
> std::exception::what: boost::bad_any_cast: failed conversion using boost::any_cast

Addressed in:
5393fb24676970b5ff9a66d43a6fc6fb7146674b

> If one uses other import options than --fastimport:
> bin$ ./peaks import --path ~/1/
> searching config file peaks_config
> config file found!
> 08/13/19 11:23:37: Starting unpacker
> Threads: 2
> Searching for certificates in: "/home/ubuntu/1/"
> Found 1 keys to import
> Key per Thread: 1
> 08/13/19 11:23:37: Starting dump read
> Segmentation fault (core dumped)

Addressed in ab7ad6330e60bb913157e0c4967ceac549f6c03b

The main logic (aside bugs) with the behavior you obeserved is that "import" is basically a "import --fastimport" + "unpack". 

To have the bare minimum keyserver functionality (just reconcile) is necessary just to have the key material ("import --fastimport"), build the ptree ("build") and then recon ("recon").

To have the full functionality, like search and download of keys is necessary to either do a full import instead of the fastimport OR run the unpacker in the background after a fastimport.

The reasons behind the split import/fastimport is that the unpacking procedure is time consuming, and can be deferred because not really mandatory for the keyserver basic functionality

Lastly note that running the unpacker in background is necessary anyway because new key material fetched from other keyserver is not unpacked on the fly for performances reasons

I should add this reasonings to README for clarity
